<a href="https://colab.research.google.com/github/SaipoojithaNamani/python7/blob/main/python7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.random.randint(20,60,15)

In [3]:
a

array([36, 50, 26, 29, 37, 49, 40, 44, 56, 33, 42, 45, 24, 25, 39])

In [5]:
a.ndim #to chrck dimension of the array

1

In [6]:
58,31,29,59,52,39,39,52



(58, 31, 29, 59, 52, 39, 39, 52)

In [7]:
a[-2:-10:-1] #slicing

array([25, 24, 45, 42, 33, 56, 44, 40])

In [15]:
np.random.seed(94)
b=np.random.randint(15,50,(7,8))
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [16]:
b[2] # 2 row in teo dimensional array

array([30, 41, 26, 21, 28, 29, 17, 38])

In [17]:
a[2] # accesing 2nd element of array in one dimensional

26

In [18]:
b[4]

array([23, 30, 25, 34, 42, 16, 39, 35])

In [19]:
b[-1] # or b[6]

array([30, 37, 37, 17, 45, 24, 44, 39])

In [21]:
b[:,7] #aceesing 7th column

array([23, 18, 38, 35, 35, 47, 39])

In [22]:
b[:,4]

array([44, 47, 28, 48, 42, 37, 45])

In [23]:
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [24]:
b[3,1] #to access a particular number

47

In [26]:
b[6,4]

45

In [28]:
b[6,6]

44

In [29]:
b[1:5]

array([[31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35]])

In [30]:
b[1:5,1:5]

array([[29, 48, 25, 47],
       [41, 26, 21, 28],
       [47, 16, 15, 48],
       [30, 25, 34, 42]])

In [31]:
#array[row_start : row-end : row-step , col_start : col_end : col_step]
b[3:7,2:7]

array([[16, 15, 48, 22, 44],
       [25, 34, 42, 16, 39],
       [21, 45, 37, 48, 23],
       [37, 17, 45, 24, 44]])

In [32]:
b[1:7,1:7]

array([[29, 48, 25, 47, 39, 39],
       [41, 26, 21, 28, 29, 17],
       [47, 16, 15, 48, 22, 44],
       [30, 25, 34, 42, 16, 39],
       [45, 21, 45, 37, 48, 23],
       [37, 37, 17, 45, 24, 44]])

In [34]:
b[-7:-2,-7:-2]

array([[15, 18, 37, 44, 34],
       [29, 48, 25, 47, 39],
       [41, 26, 21, 28, 29],
       [47, 16, 15, 48, 22],
       [30, 25, 34, 42, 16]])

In [38]:
b[2,1]

41

In [39]:
b[2,4]

28

In [40]:
b[2,7]

38

In [41]:
b[4,1]

30

In [46]:
#31 49 45
48

48

In [49]:
b

array([[33, 15, 18, 37, 44, 34, 31, 23],
       [31, 29, 48, 25, 47, 39, 39, 18],
       [30, 41, 26, 21, 28, 29, 17, 38],
       [49, 47, 16, 15, 48, 22, 44, 35],
       [23, 30, 25, 34, 42, 16, 39, 35],
       [45, 45, 21, 45, 37, 48, 23, 47],
       [30, 37, 37, 17, 45, 24, 44, 39]])

In [50]:
np.where(b>30)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5,
        5, 5, 5, 5, 5, 6, 6, 6, 6, 6]),
 array([0, 3, 4, 5, 6, 0, 2, 4, 5, 6, 1, 7, 0, 1, 4, 6, 7, 3, 4, 6, 7, 0,
        1, 3, 4, 5, 7, 1, 2, 4, 6, 7]))